GET http://localhost:3000/api/users


###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "username": "admin2",
    "password": "admin"
}

###
POST http://localhost:3000/api/users
Content-Type: application/json
{
    //"username": "admin2",
    "email": "admin@admin.com",
    "password": "admin2",
    "isBarber": true
}


###
POST http://localhost:3000/api/schedule
Content-Type: application/json
{
    "date": "2023-06-19",
    "time":"12:30:05",
    "barber": "648421125c78bb488963fdea"
}